apiVersion: v1
kind: Pod
metadata:
  name: busybox
  namespace: default
  labels:
    app: busybox
    course_id: a
spec:
  schedulerName: SchedulerPluginAgent
  containers:
  - name: busybox
    image: busybox:1.34
    command:
    - "/bin/sh"
    - "-c"
    - "sleep 3600"
    imagePullPolicy: IfNotPresent