apiVersion: v1
kind: ConfigMap
metadata:
  name: mokuberl-schedule-extender-config
  namespace: kube-system
data:
  mokuberl-schedule-extender-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: SchedulerPluginAgent
      plugins:
        score:
          disabled:
          - name: NodeResourcesBalancedAllocation
          - name: NodeResourcesLeastAllocated
          - name: PodTopologySpread
          - name: SelectorSpread
          enabled:
          - name: StatisticsBasedLoadVariationBalancing
            weight: 1
          - name: RLScheduler
            weight: 1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mokuberl-schedule-extender-deploy
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      component: mokuberl-schedule-extender
  template:
    metadata:
      labels:
        component: mokuberl-schedule-extender
    spec:
      serviceAccount: mokuberl-sa
      priorityClassName: system-cluster-critical
      volumes:
        - name: mokuberl-schedule-extender-config
          configMap:
            name: mokuberl-schedule-extender-config
      containers:
        - name: mokuberl-schedule-extender-ctrl
          image: registry.cn-hangzhou.aliyuncs.com/charstal/scheduler-plugin-agent:v0.0.1
          imagePullPolicy: Always
          env:
            - name: LOAD_MONITOR_ADDRESS
              value: http://load-monitor-svc.default.svc.cluster.local:2020
          args:
            - schedule-extender
            - --config=/scheduler/mokuberl-schedule-extender-config.yaml
            - --v=6
          resources:
            requests:
              cpu: "50m"
          volumeMounts:
            - name: mokuberl-schedule-extender-config
              mountPath: /scheduler
