apiVersion: v1
kind: ConfigMap
metadata:
  name: schedule-extender-config
  namespace: kube-system
data:
  schedule-extender-config.yaml: |
    apiVersion: kubescheduler.config.k8s.io/v1beta1
    kind: KubeSchedulerConfiguration
    leaderElection:
      leaderElect: false
    profiles:
    - schedulerName: node-resource-balanced-allocation
      plugins:
        score:
          disabled:
          - name: NodeResourcesLeastAllocated
          - name: PodTopologySpread
          - name: SelectorSpread
    - schedulerName: node-resource-least-allocated
      plugins:
        score:
          disabled:
          - name: NodeResourcesBalancedAllocation
          - name: PodTopologySpread
          - name: SelectorSpread
    - schedulerName: pod-topolog-spread
      plugins:
        score:
          disabled:
          - name: NodeResourcesBalancedAllocation
          - name: NodeResourcesLeastAllocated
          - name: SelectorSpread
    - schedulerName: selector-spread
      plugins:
        score:
          disabled:
          - name: NodeResourcesBalancedAllocation
          - name: NodeResourcesLeastAllocated
          - name: PodTopologySpread
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: my-scheduler
  namespace: kube-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: my-scheduler-as-kube-scheduler
subjects:
  - kind: ServiceAccount
    name: my-scheduler
    namespace: kube-system
roleRef:
  kind: ClusterRole
  name: mokuberl-cr
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    component: kube-scheduler
    tier: control-plane
  name: kube-scheduler-for-benchmark
  namespace: kube-system
spec:
  serviceAccountName: my-scheduler
  containers:
    - command:
        - kube-scheduler
        - --authentication-kubeconfig=/etc/kubernetes/scheduler.conf
        - --authorization-kubeconfig=/etc/kubernetes/scheduler.conf
        #    - --bind-address=127.0.0.1
        - --kubeconfig=/etc/kubernetes/scheduler.conf
        - --leader-elect=true
        - --config=/schedule-extender-config/schedule-extender-config.yaml
        - --port=0
      image: registry.aliyuncs.com/google_containers/kube-scheduler:v1.20.3
      imagePullPolicy: IfNotPresent
      name: kube-scheduler
      resources:
        requests:
          cpu: 100m
      volumeMounts:
        - mountPath: /etc/kubernetes/scheduler.conf
          name: kubeconfig
          readOnly: true
        - mountPath: /schedule-extender-config
          name: extender-config
          readOnly: true
  #  hostNetwork: true
  priorityClassName: system-node-critical
  volumes:
    - hostPath:
        path: /etc/kubernetes/scheduler.conf
        type: FileOrCreate
      name: kubeconfig
    - configMap:
        name: schedule-extender-config
      name: extender-config
status: {}
