apiVersion: apps/v1
kind: Deployment
metadata:
  name: memory-test-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: memory-test
  template:
    metadata:
      labels:
        app: memory-test
    spec:
      schedulerName: RLScheduler
      containers:
      - name: memory-test
        image: registry.cn-shanghai.aliyuncs.com/charstal/memory-test
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 30m
            memory: 500Mi