apiVersion: batch/v1
kind: Job
metadata:
  name: random-load-job
spec:
  template:
    spec:
      # schedulerName: DemoScheduler
      containers:
        - name: random-load
          image: registry.cn-shanghai.aliyuncs.com/charstal/random_load
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 200m
              memory: 400Mi
            limits:
              cpu: 400m
              memory: 800Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/random-load
      volumes:
        - name: config-volume
          configMap:
            name: random-load-config
      restartPolicy: Never
  completions: 3
  parallelism: 1
