apiVersion: batch/v1
kind: Job
metadata:
  name: random-load-job
spec:
  template:
    spec:
      schedulerName: node-resource-least-allocated
      containers:
        - name: random-load
          image: registry.cn-shanghai.aliyuncs.com/charstal/random_load
          imagePullPolicy: Always
          resources:
            requests:
              cpu: 300m
              memory: 1000Mi
            limits:
              cpu: 500m
              memory: 1500Mi
          volumeMounts:
            - name: config-volume
              mountPath: /etc/random-load
      volumes:
        - name: config-volume
          configMap:
            name: random-load-config
      restartPolicy: Never
  completions: 1
  # parallelism: 3
