apiVersion: apps/v1
kind: Deployment
metadata:
  name: balanced-test-deploy
spec:
  replicas: 3
  selector:
    matchLabels:
      app: balanced-test
  template:
    metadata:
      labels:
        app: balanced-test
    spec:
      schedulerName: RLScheduler
      containers:
      - name: cpu-test
        image: registry.cn-shanghai.aliyuncs.com/charstal/cpu-test
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 200m
            memory: 30Mi
      - name: memory-test
        image: registry.cn-shanghai.aliyuncs.com/charstal/memory-test:100MB
        imagePullPolicy: IfNotPresent
        resources:
          limits:
            cpu: 30m
            memory: 150Mi